import Footer from "@/components/shared/Footer/Footer";
import "./globals.css";
import Navbar from "@/components/shared/Navbar/Navbar";

export const metadata = {
  metadataBase: new URL("http://localhost:3000"),
  title: {
    default: "Blog Application",
    template: "%s | Blog Application",
  },
  description: "Generated by create next app",
  twitter: {
    card: "summary_large_image",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={" max-w-[1400px] mx-auto font-poppins"}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
